### PR TITLE
Update script to Python 3; Add Trigger Happy, Gill Grunt and Zook.

### PR DESCRIPTION
**Pull request by vifino**
As per the title - made the script run under Python 3, which is the only Python you should run.

I also added my three Skylander figurines. Not sure about the order of the file or the comments in brackets before the names.
Perhaps this should be sorted somehow?

Kind regards,
vifino.

### CODE REVIEW

**Comment by V0lk3n** [comment]
Hi! Thanks so much for your Pull Request,

For the python3 script, this is not my creation but the one of NfcToys, so i suggest you to make another PR to them about it :) https://github.com/nfctoys/nfctoys

For the keys list, you should put the keys in CAPS, then i put before the keys "[Serial number / UID] Name of the Skylanders", the serial number can be found in the back of your toy ^^

Can you make the change? Then i merge the PR? Otherwise i merge as it and i make the change myself as you pref

Anyway thanks for your contribution, also to let you know, the pull request about adding the capability of the flipper zero to launch the dictionnary attack and recognize the tag is close to release. Im personally already using it by compiling the firmware with the PR and it work like a charm. Also someone has implemented algorythme to automatically found the keys so the readme will change a lot at this moment :)

Keep in mind that im learning and dont really know if collecting the keys will be usefull :) we will see

**Comment by V0lk3n** [comment]
Hi @vifino i will merge this tomorrow and made the change that i can myself tomorrow if i keep didnt getting news from your side 🙂

**Comment by vifino** [comment]
Hey! Sorry, very busy. I don't have the figurines handy anymore, so I can't get the numbers.
I can upper-case the IDs and update the script as well, but I don't have much time to do anything else.

**Comment by V0lk3n** [comment]
> Hey! Sorry, very busy. I don't have the figurines handy anymore, so I can't get the numbers.
> I can upper-case the IDs and update the script as well, but I don't have much time to do anything else.

Hi! No problem ^^ i will merge as this and made it as caps myself no worry!

Just dont forget to send your python3 script PR at NFCTOYS repo if you want to :) it can be a well know contrib ;)

Thanks again for you PR and i let you know once its merged and "CAPS fixed"

Best regard and have a nice day!

(Btw, the flipper pr as been merged, you can add the keys to nfc user dic file and it will read the skylanders sectors!)

Note : i hear that soon they will merge algo to retrieve the keys, so maybe this repo will not be usefull at this moment. We will see how its going on :) but thanks again!!

**Comment by vifino** [comment]
It's updated now, so less work for you, hopefully! :)

**Comment by V0lk3n** [comment]
Thanks so much! I merge it tommorow, im on my phone actually hehe 

Thanks!

**Pull request merged**
